export const mockCandidates: Candidate[] = [
    {
        first_name: "Daniel",
        last_name: "Ardelean",
        personal_email: "danicodes45@gmail.com",
        phone: "123-456-7890",
        address: "Hasdeu, Camin 17",
        birthday: new Date("2002-07-28"),
        gender: "Male",
        studies_type: "Masters",
        specialization: "Distributed Systems",
        study_group: "MaSD1",
        study_language: "Romanian",
        facebook_profile: "https://www.facebook.com/ardelean.danielgeorge/",
        instagram_profile: "https://www.instagram.com/_giuco/",
        recruitment_status: "Accepted",
        recruitment_campaign_id: "1",
    },
    {
        first_name: "Radu",
        last_name: "Bradu",
        personal_email: "some@gmail.com",
        phone: "123-456-7890",
        address: "Alta strada",
        birthday: new Date("1997-01-01"),
        gender: "Female",
        studies_type: "Bachelors",
        specialization: "Computer Science",
        study_group: "236",
        study_language: "Romanian",
        facebook_profile: "https://www.facebook.com/sidorac.radu",
        instagram_profile: "https://www.instagram.com/bradutfericit/",
        recruitment_status: "Pending",
        recruitment_campaign_id: "1",
    },
    {
        first_name: "Nume3",
        last_name: "Prenume3",
        personal_email: "n2@example.com",
        phone: "123-456-7890",
        address: "Alta strada",
        birthday: new Date("2001-01-01"),
        gender: "Female",
        studies_type: "Bachelors",
        specialization: "Mathematics and Informatics",
        study_group: "311",
        study_language: "English",
        facebook_profile: "https://www.facebook.com/ardelean.danielgeorge/",
        instagram_profile: "https://www.instagram.com/_giuco/",
        recruitment_status: "Rejected",
        recruitment_campaign_id: "1",
    },
    {
        first_name: "Nume4",
        last_name: "Prenume4",
        personal_email: "some@gmail.com",
        phone: "123-456-7890",
        address: "Alta strada4",
        birthday: new Date("2000-01-01"),
        gender: "Male",
        studies_type: "Bachelors",
        specialization: "Computer Science",
        study_group: "232",
        study_language: "Romanian",
        facebook_profile: "https://www.facebook.com/sidorac.radu",
        instagram_profile: "https://www.instagram.com/bradutfericit/",
        recruitment_status: "Accepted",
        recruitment_campaign_id: "1",
    },
    {
        first_name: "Nume5",
        last_name: "Prenume5",
        personal_email: "some@gmail.com",
        phone: "123-456-7890",
        address: "Alta strada4",
        birthday: new Date("2000-03-01"),
        gender: "Male",
        studies_type: "Bachelors",
        specialization: "Computer Science",
        study_group: "233",
        study_language: "Romanian",
        facebook_profile: "https://www.facebook.com/sidorac.radu",
        instagram_profile: "https://www.instagram.com/bradutfericit/",
        recruitment_status: "Pending",
        recruitment_campaign_id: "2",
    },
    {
        first_name: "Nume6",
        last_name: "Prenume6",
        personal_email: "some@gmail.com",
        phone: "123-456-7890",
        address: "Alta strada4",
        birthday: new Date("2000-01-01"),
        gender: "Male",
        studies_type: "Bachelors",
        specialization: "Computer Science",
        study_group: "232",
        study_language: "Romanian",
        facebook_profile: "https://www.facebook.com/sidorac.radu",
        instagram_profile: "https://www.instagram.com/bradutfericit/",
        recruitment_status: "Rejected",
        recruitment_campaign_id: "1",
    },
    {
        first_name: "Nume7",
        last_name: "Prenume7",
        personal_email: "some@gmail.com",
        phone: "123-456-7890",
        address: "Alta strada4",
        birthday: new Date("2002-05-16"),
        gender: "Female",
        studies_type: "Bachelors",
        specialization: "Computer Science",
        study_group: "234",
        study_language: "English",
        facebook_profile: "https://www.facebook.com/sidorac.radu",
        instagram_profile: "https://www.instagram.com/bradutfericit/",
        recruitment_status: "Pending",
        recruitment_campaign_id: "1",
    },
    {
        first_name: "Nume8",
        last_name: "Prenume8",
        personal_email: "some@gmail.com",
        phone: "123-456-7890",
        address: "Alta strada4",
        birthday: new Date("2000-01-01"),
        gender: "Male",
        studies_type: "Bachelors",
        specialization: "Computer Science",
        study_group: "232",
        study_language: "Romanian",
        facebook_profile: "https://www.facebook.com/sidorac.radu",
        instagram_profile: "https://www.instagram.com/bradutfericit/",
        recruitment_status: "Accepted",
        recruitment_campaign_id: "1",
    },
    {
        first_name: "Nume9",
        last_name: "Prenume9",
        personal_email: "some@gmail.com",
        phone: "123-456-7890",
        address: "Alta strada4",
        birthday: new Date("2000-01-01"),
        gender: "Male",
        studies_type: "Bachelors",
        specialization: "Computer Science",
        study_group: "232",
        study_language: "Romanian",
        facebook_profile: "https://www.facebook.com/sidorac.radu",
        instagram_profile: "https://www.instagram.com/bradutfericit/",
        recruitment_status: "Pending",
        recruitment_campaign_id: "1",
    },
    {
        first_name: "Nume10",
        last_name: "Prenume10",
        personal_email: "some@gmail.com",
        phone: "123-456-7890",
        address: "Alta strada4",
        birthday: new Date("2000-01-01"),
        gender: "Male",
        studies_type: "Bachelors",
        specialization: "Computer Science",
        study_group: "232",
        study_language: "Romanian",
        facebook_profile: "https://www.facebook.com/sidorac.radu",
        instagram_profile: "https://www.instagram.com/bradutfericit/",
        recruitment_status: "Rejected",
        recruitment_campaign_id: "1",
    },
    {
        first_name: "Nume11",
        last_name: "Prenume11",
        personal_email: "some@gmail.com",
        phone: "123-456-7890",
        address: "Alta strada4",
        birthday: new Date("2000-01-01"),
        gender: "Male",
        studies_type: "Bachelors",
        specialization: "Computer Science",
        study_group: "232",
        study_language: "Romanian",
        facebook_profile: "https://www.facebook.com/sidorac.radu",
        instagram_profile: "https://www.instagram.com/bradutfericit/",
        recruitment_status: "Pending",
        recruitment_campaign_id: "1",
    },
    {
        first_name: "Nume12",
        last_name: "Prenume12",
        personal_email: "some@gmail.com",
        phone: "123-456-7890",
        address: "Alta strada4",
        birthday: new Date("2000-01-01"),
        gender: "Male",
        studies_type: "Bachelors",
        specialization: "Computer Science",
        study_group: "232",
        study_language: "Romanian",
        facebook_profile: "https://www.facebook.com/sidorac.radu",
        instagram_profile: "https://www.instagram.com/bradutfericit/",
        recruitment_status: "Accepted",
        recruitment_campaign_id: "1",
    },
];